version: '3.0'

services:
  ui:
    image: samtecspg/articulate-ui:0.12.1
    ports: ['0.0.0.0:3000:3000']
    networks: ['botsharp-network']
    environment:
     - API_URL: 127.0.0.1:3000
  
  api:
    image: samtecspg/articulate-api:0.12.1
    ports: ['0.0.0.0:7500:7500']
    networks: ['botsharp-network']
    entrypoint: ['node', 'start.js']

  botsharp:
    image: botsharpdocker/botsharp-rasa:latest
    ports: ['0.0.0.0:5000:5000']
    networks: ['botsharp-network']

networks: {botsharp-network: {}}
